from django.db import models
from django.conf import settings


class Recommendation(models.Model):
    """
    Stores generated recommendations for a user.
    Each recommendation is tied to the user's profile snapshot at generation time.
    """

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]

    CONFIDENCE_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='recommendations',
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    confidence = models.CharField(max_length=10, choices=CONFIDENCE_CHOICES, default='medium')
    algorithm_used = models.CharField(
        max_length=50, default='hybrid',
        help_text='content_based / collaborative / hybrid',
    )

    # ==================== EXERCISE PLAN ====================

    workout_split = models.CharField(
        max_length=100, blank=True, default='',
        help_text='e.g. Push/Pull/Legs, Upper/Lower, Full Body',
    )
    exercise_plan = models.JSONField(
        default=list, blank=True,
        help_text='Structured workout plan: [{day, focus, exercises: [{name, muscle, equipment, sets, reps}]}]',
    )
    workout_days_per_week = models.PositiveIntegerField(default=3)

    # ==================== DIET PLAN ====================

    diet_plan = models.JSONField(
        default=dict, blank=True,
        help_text='Structured meal plan: {breakfast, lunch, dinner, snacks}',
    )
    daily_calorie_target = models.FloatField(null=True, blank=True)
    macro_split = models.JSONField(
        default=dict, blank=True,
        help_text='Macronutrient split: {protein_g, carbs_g, fat_g}',
    )

    # ==================== HEALTH GUIDANCE ====================

    health_notes = models.TextField(
        blank=True, default='',
        help_text='Medical-aware guidelines based on chronic diseases, BP, etc.',
    )

    # ==================== LLM & RAG ====================

    llm_recommendation = models.TextField(
        blank=True, default='',
        help_text='Conversational recommendation generated by LLM via RAG.',
    )
    rag_context_chunks = models.JSONField(
        default=list, blank=True,
        help_text='Simplified semantic chunks retrieved for the RAG process.',
    )

    # ==================== PROFILE SNAPSHOT ====================

    profile_snapshot = models.JSONField(
        default=dict, blank=True,
        help_text='Snapshot of user profile at recommendation time for auditability.',
    )

    # ==================== CHECK-IN SNAPSHOT ====================

    checkin_snapshot = models.JSONField(
        default=dict, blank=True,
        help_text='Snapshot of latest check-in at recommendation time for auditability.',
    )

    # ==================== EXPLANATION ====================

    explanation = models.TextField(
        blank=True, default='',
        help_text='Human-readable explanation of how the recommendation was generated.',
    )

    # ==================== SIMILARITY METADATA ====================

    similar_profiles_count = models.PositiveIntegerField(
        default=0,
        help_text='Number of similar profiles found in the dataset.',
    )
    avg_similarity_score = models.FloatField(
        null=True, blank=True,
        help_text='Average cosine similarity score with matched profiles.',
    )

    # ==================== TIMESTAMPS ====================

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Recommendation'
        verbose_name_plural = 'Recommendations'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.email} — {self.workout_split} ({self.created_at.strftime('%Y-%m-%d')})"


class DatasetEntry(models.Model):
    """
    Normalized dataset entry from all 4 merged CSV datasets.
    Used as the corpus for the recommendation engine's similarity matching.
    """

    SOURCE_CHOICES = [
        ('dataset_1', 'Diet & Exercise Plan (nimsara55)'),
        ('dataset_2', 'Gym Recommendation (Mendeley)'),
        ('dataset_3', 'Diet Recommendations (ziya07)'),
        ('dataset_4', 'Medical Diet Recommendations (ziya07)'),
    ]

    source = models.CharField(max_length=15, choices=SOURCE_CHOICES)
    source_id = models.CharField(max_length=50, blank=True, default='')

    # Standardized feature columns
    age = models.PositiveIntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, blank=True, default='')
    height = models.FloatField(null=True, blank=True, help_text='In cm')
    weight = models.FloatField(null=True, blank=True, help_text='In kg')
    bmi = models.FloatField(null=True, blank=True)
    bmi_level = models.CharField(max_length=15, blank=True, default='')

    # Medical
    chronic_disease = models.CharField(max_length=100, blank=True, default='')
    hypertension = models.BooleanField(null=True, blank=True)
    diabetes = models.BooleanField(null=True, blank=True)

    # Lifestyle
    activity_level = models.CharField(max_length=20, blank=True, default='')
    exercise_frequency = models.PositiveIntegerField(null=True, blank=True)
    daily_steps = models.PositiveIntegerField(null=True, blank=True)
    sleep_quality = models.CharField(max_length=10, blank=True, default='')
    smoking_habit = models.BooleanField(null=True, blank=True)
    alcohol_consumption = models.CharField(max_length=15, blank=True, default='')

    # Diet
    dietary_preference = models.CharField(max_length=30, blank=True, default='')
    caloric_intake = models.FloatField(null=True, blank=True)
    protein_intake = models.FloatField(null=True, blank=True)
    carbohydrate_intake = models.FloatField(null=True, blank=True)
    fat_intake = models.FloatField(null=True, blank=True)
    cuisine_preference = models.CharField(max_length=100, blank=True, default='')
    food_aversion = models.TextField(blank=True, default='')

    # Fitness
    fitness_goal = models.CharField(max_length=30, blank=True, default='')
    workout_type = models.CharField(max_length=30, blank=True, default='')
    fitness_type = models.CharField(max_length=30, blank=True, default='')

    # Target labels / recommendations from dataset
    exercise_plan = models.TextField(blank=True, default='')
    equipment = models.TextField(blank=True, default='')
    diet_recommendation = models.TextField(blank=True, default='')
    meal_plan = models.JSONField(
        default=dict, blank=True,
        help_text='{breakfast, lunch, dinner, snacks}',
    )
    general_recommendation = models.TextField(blank=True, default='')

    # Metadata
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Dataset Entry'
        verbose_name_plural = 'Dataset Entries'
        ordering = ['source', 'id']
        indexes = [
            models.Index(fields=['source']),
            models.Index(fields=['fitness_goal']),
            models.Index(fields=['age']),
            models.Index(fields=['gender']),
            models.Index(fields=['bmi_level']),
        ]

    def __str__(self):
        return f"{self.source} #{self.id} — Age {self.age}, {self.fitness_goal}"
