# Generated by Django 5.2.12 on 2026-05-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='chat_chatco_user_id_c11ba7_idx',
            old_name='chat_chatc_user_id_742f7c_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_convers_c2caf0_idx',
            old_name='chat_chatm_convers_12f78e_idx',
        ),
    ]
