# Generated by Django 5.2.12 on 2026-03-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('algorithm_used', models.CharField(default='hybrid', help_text='content_based / collaborative / hybrid', max_length=50)),
                ('workout_split', models.CharField(blank=True, default='', help_text='e.g. Push/Pull/Legs, Upper/Lower, Full Body', max_length=100)),
                ('exercise_plan', models.JSONField(blank=True, default=list, help_text='Structured workout plan: [{day, focus, exercises: [{name, muscle, equipment, sets, reps}]}]')),
                ('workout_days_per_week', models.PositiveIntegerField(default=3)),
                ('diet_plan', models.JSONField(blank=True, default=dict, help_text='Structured meal plan: {breakfast, lunch, dinner, snacks}')),
                ('daily_calorie_target', models.FloatField(blank=True, null=True)),
                ('macro_split', models.JSONField(blank=True, default=dict, help_text='Macronutrient split: {protein_g, carbs_g, fat_g}')),
                ('health_notes', models.TextField(blank=True, default='', help_text='Medical-aware guidelines based on chronic diseases, BP, etc.')),
                ('profile_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of user profile at recommendation time for auditability.')),
                ('similar_profiles_count', models.PositiveIntegerField(default=0, help_text='Number of similar profiles found in the dataset.')),
                ('avg_similarity_score', models.FloatField(blank=True, help_text='Average cosine similarity score with matched profiles.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('dataset_1', 'Diet & Exercise Plan (nimsara55)'), ('dataset_2', 'Gym Recommendation (Mendeley)'), ('dataset_3', 'Diet Recommendations (ziya07)'), ('dataset_4', 'Medical Diet Recommendations (ziya07)')], max_length=15)),
                ('source_id', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('height', models.FloatField(blank=True, help_text='In cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='In kg', null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_level', models.CharField(blank=True, default='', max_length=15)),
                ('chronic_disease', models.CharField(blank=True, default='', max_length=100)),
                ('hypertension', models.BooleanField(blank=True, null=True)),
                ('diabetes', models.BooleanField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, default='', max_length=20)),
                ('exercise_frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_quality', models.CharField(blank=True, default='', max_length=10)),
                ('smoking_habit', models.BooleanField(blank=True, null=True)),
                ('alcohol_consumption', models.CharField(blank=True, default='', max_length=15)),
                ('dietary_preference', models.CharField(blank=True, default='', max_length=30)),
                ('caloric_intake', models.FloatField(blank=True, null=True)),
                ('protein_intake', models.FloatField(blank=True, null=True)),
                ('carbohydrate_intake', models.FloatField(blank=True, null=True)),
                ('fat_intake', models.FloatField(blank=True, null=True)),
                ('cuisine_preference', models.CharField(blank=True, default='', max_length=100)),
                ('food_aversion', models.TextField(blank=True, default='')),
                ('fitness_goal', models.CharField(blank=True, default='', max_length=30)),
                ('workout_type', models.CharField(blank=True, default='', max_length=30)),
                ('fitness_type', models.CharField(blank=True, default='', max_length=30)),
                ('exercise_plan', models.TextField(blank=True, default='')),
                ('equipment', models.TextField(blank=True, default='')),
                ('diet_recommendation', models.TextField(blank=True, default='')),
                ('meal_plan', models.JSONField(blank=True, default=dict, help_text='{breakfast, lunch, dinner, snacks}')),
                ('general_recommendation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dataset Entry',
                'verbose_name_plural': 'Dataset Entries',
                'ordering': ['source', 'id'],
                'indexes': [models.Index(fields=['source'], name='recommendat_source_49aebe_idx'), models.Index(fields=['fitness_goal'], name='recommendat_fitness_a641b7_idx'), models.Index(fields=['age'], name='recommendat_age_4ef7b9_idx'), models.Index(fields=['gender'], name='recommendat_gender_d73a0f_idx'), models.Index(fields=['bmi_level'], name='recommendat_bmi_lev_f2c81e_idx')],
            },
        ),
    ]
