# Generated by Django 5.2.12 on 2026-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='llm_recommendation',
            field=models.TextField(blank=True, default='', help_text='Conversational recommendation generated by LLM via RAG.'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rag_context_chunks',
            field=models.JSONField(blank=True, default=list, help_text='Simplified semantic chunks retrieved for the RAG process.'),
        ),
    ]
