# Generated by Django 5.2.13 on 2026-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendation_llm_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='checkin_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of latest check-in at recommendation time for auditability.'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Human-readable explanation of how the recommendation was generated.'),
        ),
    ]
