# Generated by Django 5.2.12 on 2026-05-06 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_recommendation_checkin_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('too_easy', models.BooleanField(default=False)),
                ('too_hard', models.BooleanField(default=False)),
                ('pain_reported', models.BooleanField(default=False)),
                ('pain_area', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_feedbacks', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercise Feedback',
                'verbose_name_plural': 'Exercise Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='MealFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eaten', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('too_expensive', models.BooleanField(default=False)),
                ('hard_to_prepare', models.BooleanField(default=False)),
                ('disliked_ingredient', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_feedbacks', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Feedback',
                'verbose_name_plural': 'Meal Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('satisfaction_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('liked_workout', models.BooleanField(blank=True, null=True)),
                ('liked_diet', models.BooleanField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='UserPreferenceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked_exercises', models.JSONField(blank=True, default=list)),
                ('preferred_exercises', models.JSONField(blank=True, default=list)),
                ('disliked_foods', models.JSONField(blank=True, default=list)),
                ('preferred_foods', models.JSONField(blank=True, default=list)),
                ('preferred_workout_duration', models.IntegerField(blank=True, null=True)),
                ('preferred_intensity', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference Memory',
                'verbose_name_plural': 'User Preference Memories',
            },
        ),
    ]
