# Generated by Django 5.2.12 on 2026-03-29 20:32

import fitness_backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[fitness_backend.validators.validate_age])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('height', models.FloatField(help_text='Height in cm', validators=[fitness_backend.validators.validate_height])),
                ('weight', models.FloatField(help_text='Weight in kg', validators=[fitness_backend.validators.validate_weight])),
                ('bmi', models.FloatField(blank=True, help_text='Auto-calculated BMI', null=True)),
                ('bmi_level', models.CharField(blank=True, choices=[('underweight', 'Underweight'), ('normal', 'Normal'), ('overweight', 'Overweight'), ('obese', 'Obese')], help_text='Auto-determined from BMI', max_length=15)),
                ('chronic_disease', models.CharField(blank=True, default='', help_text='Diabetes, Heart Disease, Hypertension, Obesity, None', max_length=100)),
                ('hypertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('cholesterol', models.PositiveIntegerField(blank=True, help_text='mg/dL', null=True)),
                ('genetic_risk', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=10)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('low', 'Low'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='moderate', max_length=15)),
                ('exercise_frequency', models.PositiveIntegerField(default=3, help_text='Days per week (1-7)')),
                ('daily_steps', models.PositiveIntegerField(blank=True, help_text='From wearable data', null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good')], default='good', max_length=10)),
                ('smoking_habit', models.BooleanField(default=False)),
                ('alcohol_consumption', models.CharField(blank=True, choices=[('none', 'None'), ('occasional', 'Occasional'), ('regular', 'Regular')], default='none', max_length=15)),
                ('avg_heart_rate', models.PositiveIntegerField(blank=True, help_text='Wearable device data', null=True)),
                ('dietary_preference', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('mediterranean', 'Mediterranean'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('caloric_intake', models.FloatField(blank=True, help_text='Daily calories target', null=True)),
                ('protein_intake', models.FloatField(blank=True, help_text='Grams/day', null=True)),
                ('carbohydrate_intake', models.FloatField(blank=True, help_text='Grams/day', null=True)),
                ('fat_intake', models.FloatField(blank=True, help_text='Grams/day', null=True)),
                ('cuisine_preference', models.CharField(blank=True, default='', max_length=100)),
                ('food_aversion', models.TextField(blank=True, default='', help_text='Foods to avoid')),
                ('fitness_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('endurance', 'Endurance')], default='maintenance', max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=15)),
                ('preferred_workout_type', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('hiit', 'HIIT'), ('mixed', 'Mixed')], default='mixed', max_length=15)),
                ('available_equipment', models.CharField(choices=[('full_gym', 'Full Gym'), ('dumbbells', 'Dumbbells Only'), ('bodyweight', 'Bodyweight Only'), ('home_gym', 'Home Gym'), ('resistance_bands', 'Resistance Bands')], default='full_gym', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health Profile',
                'verbose_name_plural': 'Health Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
