# Generated by Django 5.2.13 on 2026-05-05 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the check-in')),
                ('current_weight', models.FloatField(blank=True, help_text='Weight in kg (optional — use if different from profile)', null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good')], default='good', max_length=10)),
                ('sleep_hours', models.FloatField(blank=True, help_text='Hours slept last night', null=True)),
                ('daily_steps', models.PositiveIntegerField(blank=True, null=True)),
                ('energy_level', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Energy level 1-5')),
                ('soreness_level', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Soreness level 1-5')),
                ('stress_level', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Stress level 1-5')),
                ('resting_heart_rate', models.PositiveIntegerField(blank=True, help_text='BPM from wearable', null=True)),
                ('workout_completed', models.BooleanField(default=False)),
                ('pain_or_injury', models.BooleanField(default=False)),
                ('injury_area', models.CharField(blank=True, default='', max_length=100)),
                ('available_minutes', models.PositiveIntegerField(blank=True, help_text='Minutes available for workout today', null=True)),
                ('preferred_intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Check-In',
                'verbose_name_plural': 'Daily Check-Ins',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
