# Generated by Django 5.2.12 on 2026-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_replace_dailycheckin_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofile',
            name='dietary_preference',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('regular', 'Regular'), ('low_sodium', 'Low Sodium'), ('low_sugar', 'Low Sugar'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('mediterranean', 'Mediterranean'), ('no_preference', 'No Preference')], default='no_preference', max_length=20),
        ),
    ]
